name: fmr-stdproblem
channels:
  - http://conda.anaconda.org/maxalbert
dependencies:
  - python=2.7
  - click
  - functools32
  - matplotlib==1.5.1.post960+g628427a
  - nose
  - numpy
  - oommf=12a5bis_20120928
  - scipy
  - pip:
    - pathlib
